[build]
  publish = "dist/public"
  command = "node build-netlify.js"

[build.environment]
  NODE_VERSION = "20"
  # Netlify automatically provides NETLIFY_DATABASE_URL for Neon database connections

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/simple-login"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 5000