[build]
  publish = "dist/public"
  command = "vite build"

[build.environment]
  NODE_VERSION = "20"

# Core API Routes
[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/plans"
  to = "/.netlify/functions/plans"
  status = 200

[[redirects]]
  from = "/api/signals"
  to = "/.netlify/functions/signals"
  status = 200

[[redirects]]
  from = "/api/signals/*"
  to = "/.netlify/functions/signals"
  status = 200

# Payment Gateway Routes
[[redirects]]
  from = "/api/yoco/payment"
  to = "/.netlify/functions/payments"
  status = 200

[[redirects]]
  from = "/api/ozow/payment"
  to = "/.netlify/functions/payments"
  status = 200

[[redirects]]
  from = "/api/yoco/notify"
  to = "/.netlify/functions/webhooks"
  status = 200

[[redirects]]
  from = "/api/ozow/notify"
  to = "/.netlify/functions/webhooks"
  status = 200

# Admin Routes
[[redirects]]
  from = "/api/admin/users"
  to = "/.netlify/functions/admin"
  status = 200

[[redirects]]
  from = "/api/admin/users/*/subscription"
  to = "/.netlify/functions/admin"
  status = 200

[[redirects]]
  from = "/api/admin/users/*/create-trial"
  to = "/.netlify/functions/admin"
  status = 200

[[redirects]]
  from = "/api/admin/signals"
  to = "/.netlify/functions/admin-signals"
  status = 200

[[redirects]]
  from = "/api/admin/signals/*"
  to = "/.netlify/functions/admin-signals"
  status = 200

# User Routes
[[redirects]]
  from = "/api/user/subscription-status"
  to = "/.netlify/functions/user"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 5000